baseURL = 'https://nhathoang79.github.io/'
languageCode = 'vi-vn'
title = "Mai Tráº§n Nháº­t HoÃ ng | Network Engineer."
theme = 'PaperMod'


[markup.goldmark.renderer]
    unsafe = true
defaultTheme = "dark"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    [params.profileMode]
        enabled = true
        title = "Mai Tráº§n Nháº­t HoÃ ng "
        subtitle = "ðŸš€ ChuyÃªn gia Há»‡ thá»‘ng & Máº¡ng | Java & JavaScript Developer | HUTECH"
        imageUrl = "anhdep.jpg"
        imageWidth = 380
        imageHeight = 400
        imageDisplay = "Rounded"
        buttons = [
            { name = "Xem bÃ i viáº¿t", url = "/posts" },
            { name = "Dá»± Ã¡n", url = "/projects" },
            { name = "Profile", url = "/about" }
        ] 
socialIcons = [
        { name = "facebook", url = "https://facebook.com/ten-cua-ban" },
        { name = "github", url = "https://github.com/ten-cua-ban" },
        { name = "instagram", url = "https://instagram.com/ten-cua-ban" }
    ]

[menu]
    [[menu.main]]
        name = "BÃ i Viáº¿t"
        url = "/posts"
        weight = 10
    [[menu.main]]
        name = "Dá»± Ã¡n"
        url = "/projects" 
        weight = 15
    [[menu.main]]
        name = "Profile"
        url = "/about"
        weight = 20
    [[menu.main]]
        name = "LiÃªn há»‡"
        url = "/contact"
        weight = 28